---
- name: Atualização cache "APT UPDATE"
  apt:
    update_cache: yes

- name: Instalação do NGINX "APT INSTALL NGINX"
  apt:
    name: nginx

- name: Garantindo site
  copy:
    src: site2/
    dest: /var/www/html

- service:
    name: nginx
    state: started